In [ ]:
from gensim.models import Word2Vec, KeyedVectors
from google.colab import drive
drive.mount('/content/drive')

# At this stage Colab will try to access your Google Drive account.
 # Enter the credentials of your Google Drive account.
path = "/content/drive/MyDrive/GoogleNews-vectors-negative300.bin"

# Provide the complete path of the ‘GoogleNews’ file 
# stored in your Google Drive account.
model = KeyedVectors.load_word2vec_format(path, binary=True, limit=200000) 

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#vec1
Vec1 = model['Marie_Curie'] - model['physics'] + model['politics']
model.most_similar([Vec1])

[('Marie_Curie', 0.6391899585723877),
 ('politics', 0.45687681436538696),
 ('Sue_Ryder', 0.4075208902359009),
 ('Breakthrough_Breast_Cancer', 0.37573349475860596),
 ('Margaret_Thatcher', 0.3684638738632202),
 ('Marie_Curie_Cancer', 0.3580324649810791),
 ('politicians', 0.34992516040802),
 ('Breast_Cancer_Care', 0.34824055433273315),
 ('Mrs_Thatcher', 0.34574592113494873),
 ('politicans', 0.3389204740524292)]

In [ ]:
#vec2
Vec2 = model['Cowboys'] - model['Dallas'] + model['Miami']
model.most_similar([Vec2])

[('Cowboys', 0.7327903509140015),
 ('Dolphins', 0.7073556184768677),
 ('Miami_Dolphins', 0.6461875438690186),
 ('Broncos', 0.6419292688369751),
 ('Seminoles', 0.6188381910324097),
 ('Gators', 0.6109527945518494),
 ('Hokies', 0.592700719833374),
 ('Dallas_Cowboys', 0.5866430401802063),
 ('Sooners', 0.5866405367851257),
 ('Cleveland_Browns', 0.5844414234161377)]

In [ ]:
#vec3
Vec3 = model['Sacramento'] - model['California'] + model['Colorado']
model.most_similar([Vec3])

[('Denver', 0.7687567472457886),
 ('Colorado', 0.7621334791183472),
 ('Sacramento', 0.7206398248672485),
 ('Grand_Junction', 0.6696534156799316),
 ('Fort_Collins', 0.6669073104858398),
 ('Boulder', 0.6501880288124084),
 ('Colorado_Springs', 0.6477946043014526),
 ('Pueblo', 0.6256301403045654),
 ('Spokane', 0.6246552467346191),
 ('Gunnison', 0.6222272515296936)]

In [ ]:
#vec4
Vec4 = model['Cowboys'] - model['Dallas'] + model['San_Francisco']
model.most_similar([Vec4])

[('Cowboys', 0.71146559715271),
 ('Giants', 0.6826242208480835),
 ('Niners', 0.6466032862663269),
 ('##ers', 0.6438729763031006),
 ('San_Francisco_##ers', 0.6088260412216187),
 ('Oakland_Raiders', 0.6043734550476074),
 ('Broncos', 0.594341516494751),
 ('Raiders', 0.5565467476844788),
 ('Seahawks', 0.5484771728515625),
 ('Dallas_Cowboys', 0.5368008613586426)]

Problem #2

In [ ]:
# 1. Load the libraries

import pandas as pd
from sklearn import preprocessing 

# 2. Read the Dataset
data = pd.read_csv('Admissions.csv')
data.head()


admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [ ]:
features = data[['gre','gpa','rank']]
type(features)

pandas.core.frame.DataFrame

In [ ]:
features[0:5]

gre   gpa  rank
0  380  3.61     3
1  660  3.67     3
2  800  4.00     1
3  640  3.19     4
4  520  2.93     4

In [ ]:
featuresScale = preprocessing.minmax_scale(data[['gre','gpa','rank']])
type(featuresScale)

numpy.ndarray

In [ ]:
#3. Scale the predictor variable values between 0 and 1
featuresScale[0:5]

array([[0.27586207, 0.77586207, 0.66666667],
       [0.75862069, 0.81034483, 0.66666667],
       [1.        , 1.        , 0.        ],
       [0.72413793, 0.53448276, 1.        ],
       [0.51724138, 0.38505747, 1.        ]])

In [ ]:
#4.Encode the response categorical variable into one-hot variable
from keras.utils import to_categorical

labels = to_categorical(data['admit'])

print(labels.shape)

(400, 2)


In [ ]:
#5.Split data into “Training” and “Testing”

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(featuresScale, labels, test_size=0.3, random_state=42)


In [ ]:
#Build the Neural Network Model Using Keras/TF software
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(5, input_dim=3, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 5)                 20        
                                                                 
 dense_5 (Dense)             (None, 2)                 12        
                                                                 
Total params: 32
Trainable params: 32
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#7. Train the Model using “Training” data
hist = model.fit(X_train, Y_train, epochs=50, batch_size=16, verbose=1)

Epoch 1/50
18/18 [==============================] - 1s 2ms/step - loss: 0.8383 - accuracy: 0.3143
Epoch 2/50
18/18 [==============================] - 0s 2ms/step - loss: 0.7779 - accuracy: 0.3143
Epoch 3/50
18/18 [==============================] - 0s 2ms/step - loss: 0.7313 - accuracy: 0.3500
Epoch 4/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6977 - accuracy: 0.4786
Epoch 5/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6744 - accuracy: 0.6321
Epoch 6/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6569 - accuracy: 0.6893
Epoch 7/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6450 - accuracy: 0.6857
Epoch 8/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6362 - accuracy: 0.6857
Epoch 9/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6298 - accuracy: 0.6893
Epoch 10/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6254 - accuracy: 0.6893
Epoch 11/50
18/18 [

In [ ]:
#8. Print values of all the weights and bias of all the neurons of the Neural Network

for layer in model.layers:
    weights, biases = layer.get_weights()
    print(layer.name)
    print("Weights:\n", weights)
    print("Biases:\n", biases)

dense_4
Weights:
 [[ 5.26383638e-01  6.09598577e-01 -3.67466211e-02  7.93090045e-01
   7.53447175e-01]
 [-4.69072968e-01 -6.58311918e-02 -2.96204865e-01 -8.49712715e-02
   1.05539553e-01]
 [-1.10419234e-04  5.46904802e-01 -6.50247097e-01  9.18126047e-01
  -6.38674855e-01]]
Biases:
 [-0.11275316 -0.14680448  0.          0.20132886  0.06604627]
dense_5
Weights:
 [[-0.4893505   0.4111073 ]
 [-0.48809087  0.01761472]
 [-0.623392   -0.59291655]
 [ 0.04366435 -0.90226656]
 [-0.1008818   1.0832626 ]]
Biases:
 [ 0.17719588 -0.17719585]


In [ ]:
#9. Predict the outcome using the “Testing” data
y_pred = model.predict(X_test)

Y_test = Y_test.argmax(axis=1)
y_pred = y_pred.argmax(axis=1)

4/4 [==============================] - 0s 2ms/step


In [ ]:
#10. Build confusion matrix
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(Y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Confusion Matrix:
 [[81  0]
 [35  4]]


In [ ]:
#11. Compute the accuracy of the predictions
accuracy = (conf_matrix[0,0]+conf_matrix[1,1])/sum(sum(conf_matrix))
print("Accuracy:", accuracy)

Accuracy: 0.7083333333333334


Problem #3

In [ ]:
#1. Load libraries
import numpy as np
import pandas as pd

#2. Corpus
corpus = ["data science professionals have promising career path"]


In [ ]:
#3. Remove stop words

def remove_stop_words(corpus):
  stop_words = ['is','a','an','will','be','become','many','in','like','and']
  results = []
  for text in corpus:
     tmp = text.split(' ')
     for stop_word in stop_words:
         if stop_word in tmp:
            tmp.remove(stop_word)
     results.append(" ".join(tmp))

  return results


In [ ]:
#4. Remove stop words
corpus = remove_stop_words(corpus)
print(corpus)

['data science professionals have promising career path']


In [ ]:
#5. Tokenize

words = []
for text in corpus:
  for word in text.split(' '):
    words.append(word)

words = sorted(set(words))
print(words)
print('Total words = ', len(words))

['career', 'data', 'have', 'path', 'professionals', 'promising', 'science']
Total words =  7


In [ ]:
#6. Generate label using skipgram
word2int = {}

for i, word in enumerate(words):
  word2int[word] = i

sentences = []
for sentence in corpus:
  sentences.append(sentence.split())

WINDOW_SIZE = 1

skipNgram_data = []
for sentence in sentences:
  for idx, word in enumerate(sentence):
    for neighbor in sentence[max(idx - WINDOW_SIZE, 0) : min(idx + WINDOW_SIZE, len(sentence)) + 1] :
      if neighbor != word:
        skipNgram_data.append([word, neighbor])

In [ ]:
#7. Skipgram
skipNgram_df = pd.DataFrame(skipNgram_data, columns = ['input','label'])
print("Window Size = 1")
print("Number of Entries = 12")
print(skipNgram_df)

Window Size = 1
Number of Entries = 12
            input          label
0            data        science
1         science           data
2         science  professionals
3   professionals        science
4   professionals           have
5            have  professionals
6            have      promising
7       promising           have
8       promising         career
9          career      promising
10         career           path
11           path         career


In [ ]:
#Window Size = 2
WINDOW_SIZE = 2

skipNgram_data = []
for sentence in sentences:
  for idx, word in enumerate(sentence):
    for neighbor in sentence[max(idx - WINDOW_SIZE, 0) : min(idx + WINDOW_SIZE, len(sentence)) + 1] :
      if neighbor != word:
        skipNgram_data.append([word, neighbor])

skipNgram_df_2 = pd.DataFrame(skipNgram_data, columns = ['input','label'])
print("Window Size = 2")
print("Number of Entries = 22")
print(skipNgram_df_2)

Window Size = 2
Number of Entries = 22
            input          label
0            data        science
1            data  professionals
2         science           data
3         science  professionals
4         science           have
5   professionals           data
6   professionals        science
7   professionals           have
8   professionals      promising
9            have        science
10           have  professionals
11           have      promising
12           have         career
13      promising  professionals
14      promising           have
15      promising         career
16      promising           path
17         career           have
18         career      promising
19         career           path
20           path      promising
21           path         career


In [ ]:
#Window Size = 3
WINDOW_SIZE = 3

skipNgram_data = []
for sentence in sentences:
  for idx, word in enumerate(sentence):
    for neighbor in sentence[max(idx - WINDOW_SIZE, 0) : min(idx + WINDOW_SIZE, len(sentence)) + 1] :
      if neighbor != word:
        skipNgram_data.append([word, neighbor])

skipNgram_df_3 = pd.DataFrame(skipNgram_data, columns = ['input','label'])
print("Window Size = 3")
print("Number of Entries = 30")
print(skipNgram_df_3)

Window Size = 3
Number of Entries = 30
            input          label
0            data        science
1            data  professionals
2            data           have
3         science           data
4         science  professionals
5         science           have
6         science      promising
7   professionals           data
8   professionals        science
9   professionals           have
10  professionals      promising
11  professionals         career
12           have           data
13           have        science
14           have  professionals
15           have      promising
16           have         career
17           have           path
18      promising        science
19      promising  professionals
20      promising           have
21      promising         career
22      promising           path
23         career  professionals
24         career           have
25         career      promising
26         career           path
27           path           have
28  

Problem #4

In [ ]:
#Hot-encoding data function

ONE_HOT_DIM = len(words)

def to_one_hot_encoding(data_point_index):
  one_hot_encoding = np.zeros(ONE_HOT_DIM)
  one_hot_encoding[data_point_index] = 1
  return one_hot_encoding

In [ ]:
#Generate Data

X = [] 
Y = []

for x, y in zip(skipNgram_df['input'], skipNgram_df['label']):
  X.append(to_one_hot_encoding(word2int[x]))
  Y.append(to_one_hot_encoding(word2int[y]))

X_train = np.asarray(X)
Y_train = np.asarray(Y)

In [ ]:
print(word2int)
print("input")
print(X_train)
print()
print("label")
print(Y_train)

{'career': 0, 'data': 1, 'have': 2, 'path': 3, 'professionals': 4, 'promising': 5, 'science': 6}
input
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]

label
[[0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
